export const DOWNLOAD_AUDIO = "DOWNLOAD_AUDIO";
export const PLAY_AUDIO = "PLAY_AUDIO";
export const PAUSE_AUDIO = "PAUSE_AUDIO";
export const CANCELLED_AUDIO = "CANCELLED_AUDIO";
export const GET_AUDIO_REF = "GET_AUDIO_REF";
