export const CREATE_PROJECT = "CREATE_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const FETCH_PROJECTS = "FETCH_PROJECTS";
export const LISTEN_TO_PROJECT_CHAT = "LISTEN_TO_PROJECT_CHAT";
export const CLEAR_COMMENTS = "CLEAR_COMMENTS";
