export const FETCH_RELEASES = "FETCH_RELEASES";

export const INCREMENT_LIKES = "INCREMENT_LIKES";
export const INCREMENT_SHARES = "INCREMENT_SHARES";
export const DECREMENT_LIKES = "DECREMENT_LIKES";
export const DECREMENT_SHARES = "DECREMENT_SHARES";
